server:
  port: 8080

spring:
  application:
    name: cloud-native-rest-api
  datasource:
    url: jdbc:mysql://localhost:3306/cloudNativeRestApi
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:org/springframework/batch/core/schema-drop-postgresql.sql
#  batch:
#    job:
#      enabled: true
#    jdbc:
#      initialize-schema: always
  jpa:
    show-sql: true #SQL 실행문 로그로 기록
    properties:
      hibernate:
        format_sql: true #pretty format
        highlight_sql : true #colored
    database-platform: org.hibernate.dialect.MySQLDialect
  data:
#    mongodb:
#      database: cyberops
#    redis:
#      host: localhost
#      port: 6379

logging:
  level:
    org.springframework.batch.item.database: DEBUG
